[package]
name = "arimaa"
version = "0.1.0"
authors = ["Justin Kur <JustinK97@hotmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-derive = "0.2.5"
num-traits = "0.2"
rand = "0.6"
failure = "*"

[dev-dependencies]
regex = "1"
